version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "5000:80"
    depends_on:
      - mariadb